name: CLHDesign
favicon: null
layout_spectrum: 0.6844941910821944
typography_spectrum: 0.8161706253886223
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9210755531676114
  lightness: 0.871768529061228
  saturation: 0.02115343208424747
  rhythmicContrast: 0.6929397895000875
purpose: []
